-- Completes the append-only intent for auth_audit_logs. The original
-- design called for revoking UPDATE/DELETE grants outright in addition to
-- the trigger; only the trigger half was ever implemented.
--
-- This is a THIRD layer, not a hole being closed. As of this migration
-- app_service is already stopped twice over:
--
--   1. RLS default-deny -- the table has only SELECT and INSERT policies,
--      and a command with no permissive policy is denied, so UPDATE and
--      DELETE match zero rows for app_service regardless of its grants.
--   2. The auth_audit_logs_no_update / auth_audit_logs_no_delete
--      triggers, which RAISE on either.
--
-- Layer 1 protects only roles that are subject to RLS. Layer 2 is the
-- only thing standing between neondb_owner (which bypasses RLS by
-- ownership) and a rewritten audit trail. Removing the grants adds a
-- third, independent barrier for app_service that does not depend on
-- policy evaluation being configured correctly -- worth having on the one
-- table whose entire value is being untamperable.
--
-- SELECT and INSERT are deliberately preserved:
--   INSERT  the app must be able to log events, including a failed login
--           with no identity context at all (hence WITH CHECK (true)).
--   SELECT  gated to admins by auth_audit_logs_select_admin_only; the
--           future audit-log viewer reads through it.
--
-- Verified 2026-07-29: no application code updates or deletes audit logs,
-- so nothing depends on the grants being present.

REVOKE UPDATE, DELETE ON auth.auth_audit_logs FROM app_service;
