use printpdf::{
    BuiltinFont, Color, Mm, Op, PdfDocument, PdfFontHandle, PdfPage, PdfSaveOptions, Point, Pt,
    RawImage, Rgb, TextItem, TextMatrix,
};

use super::layout::{
    details_column, logo_transform, paginate_rows, row_height_mm, truncate, wrap_lines,
    BODY_FONT_SIZE, BOTTOM_MARGIN_MM, COLUMNS, DETAILS_MAX_WRAP_LINES, DETAIL_LINE_HEIGHT_MM,
    HEADER_FONT_SIZE, LEFT_MARGIN_MM, LOGO_PNG_BYTES, META_FONT_SIZE, PAGE_HEIGHT_MM,
    PAGE_WIDTH_MM, ROW_HEIGHT_MM, TITLE_FONT_SIZE, TITLE_Y_MM, TOP_START_MM,
};
use super::{AuditLogPdfReport, AuditLogPdfRow};

fn black() -> Color {
    Color::Rgb(Rgb {
        r: 0.0,
        g: 0.0,
        b: 0.0,
        icc_profile: None,
    })
}

fn gray() -> Color {
    Color::Rgb(Rgb {
        r: 0.4,
        g: 0.4,
        b: 0.4,
        icc_profile: None,
    })
}

/// Places one piece of text at an absolute page position.
///
/// Deliberately `Op::SetTextMatrix { matrix: TextMatrix::Translate(..) }`,
/// not `Op::SetTextCursor`. `SetTextCursor` compiles to the raw PDF `Td`
/// operator, which moves *relative to the current line's start* -- not
/// absolute, despite what the field name suggests. A grid layout that
/// calls it repeatedly within one text section (one per cell) accumulates
/// every previous move on top of the next one, so only the very first
/// cell in a row lands where intended and everything after it drifts off
/// the visible page. `Tm` (what `SetTextMatrix` emits) replaces the text
/// matrix outright, so each call here is genuinely absolute regardless of
/// how many text draws came before it in the same section.
fn show_text_at(x_mm: f32, y_mm: f32, value: String) -> Vec<Op> {
    let point = Point::new(Mm(x_mm), Mm(y_mm));
    vec![
        Op::SetTextMatrix {
            matrix: TextMatrix::Translate(point.x, point.y),
        },
        Op::ShowText {
            items: vec![TextItem::Text(value)],
        },
    ]
}

fn set_font(font: BuiltinFont, size: f32, color: Color) -> Vec<Op> {
    vec![
        Op::SetFillColor { col: color },
        Op::SetFont {
            font: PdfFontHandle::Builtin(font),
            size: Pt(size),
        },
        Op::SetLineHeight { lh: Pt(size) },
    ]
}

fn header_row_ops(y_mm: f32) -> Vec<Op> {
    let mut ops = set_font(BuiltinFont::HelveticaBold, HEADER_FONT_SIZE, black());
    for column in COLUMNS {
        ops.extend(show_text_at(
            LEFT_MARGIN_MM + column.x_offset_mm,
            y_mm,
            column.label.to_string(),
        ));
    }
    ops
}

fn data_row_ops(row: &AuditLogPdfRow, top_y_mm: f32) -> Vec<Op> {
    let mut ops = Vec::new();

    for (column, value) in COLUMNS[..COLUMNS.len() - 1]
        .iter()
        .zip(row.single_line_cells())
    {
        ops.extend(show_text_at(
            LEFT_MARGIN_MM + column.x_offset_mm,
            top_y_mm,
            truncate(value, column.max_chars),
        ));
    }

    let details_column = details_column();
    let wrapped = wrap_lines(
        &row.details,
        details_column.max_chars,
        DETAILS_MAX_WRAP_LINES,
    );
    for (index, line) in wrapped.into_iter().enumerate() {
        ops.extend(show_text_at(
            LEFT_MARGIN_MM + details_column.x_offset_mm,
            top_y_mm - (index as f32) * DETAIL_LINE_HEIGHT_MM,
            line,
        ));
    }

    ops
}

/// Renders the full report to PDF bytes, paginating the row list across
/// as many pages as needed.
pub fn render_audit_log_pdf(report: &AuditLogPdfReport) -> Vec<u8> {
    let mut doc = PdfDocument::new(&report.report_title);

    let logo_image = RawImage::decode_from_bytes(LOGO_PNG_BYTES, &mut Vec::new())
        .expect("bundled logo PNG must decode -- it's compiled into the binary, not user input");
    let logo_transform = logo_transform(&logo_image);
    let logo_id = doc.add_image(&logo_image);

    let mut pages = Vec::new();

    // Page 1 carries the letterhead logo and the title/metadata block, so
    // its table starts lower than every subsequent page's.
    let mut first_page_ops = vec![
        Op::SaveGraphicsState,
        Op::UseXobject {
            id: logo_id,
            transform: logo_transform,
        },
        Op::StartTextSection,
    ];
    first_page_ops.extend(set_font(
        BuiltinFont::HelveticaBold,
        TITLE_FONT_SIZE,
        black(),
    ));
    first_page_ops.extend(show_text_at(
        LEFT_MARGIN_MM,
        TITLE_Y_MM,
        report.report_title.clone(),
    ));

    first_page_ops.extend(set_font(BuiltinFont::Helvetica, META_FONT_SIZE, gray()));
    let mut meta_y = TITLE_Y_MM - 10.0;
    for line in [
        format!("Generated by: {}", report.generated_by),
        format!("Generated at: {}", report.generated_at),
        // Named once here rather than repeated on every row -- the Time
        // column's per-row format (see AuditLogPdfRow's caller) is
        // compact specifically because the timezone doesn't need to
        // repeat 5000 times to stay unambiguous.
        "All times shown in UTC.".to_string(),
    ] {
        first_page_ops.extend(show_text_at(LEFT_MARGIN_MM, meta_y, line));
        meta_y -= 6.0;
    }
    for line in &report.filter_lines {
        first_page_ops.extend(show_text_at(LEFT_MARGIN_MM, meta_y, line.clone()));
        meta_y -= 5.0;
    }

    let first_table_y = meta_y - 6.0;
    first_page_ops.extend(header_row_ops(first_table_y));

    let first_page_budget_mm = first_table_y - ROW_HEIGHT_MM - BOTTOM_MARGIN_MM;
    let later_page_budget_mm = TOP_START_MM - ROW_HEIGHT_MM - BOTTOM_MARGIN_MM;
    let mut row_pages =
        paginate_rows(&report.rows, first_page_budget_mm, later_page_budget_mm).into_iter();

    let first_chunk = row_pages.next().unwrap_or(&[]);
    let mut y = first_table_y - ROW_HEIGHT_MM;
    first_page_ops.extend(set_font(BuiltinFont::Helvetica, BODY_FONT_SIZE, black()));
    for row in first_chunk {
        first_page_ops.extend(data_row_ops(row, y));
        y -= row_height_mm(row);
    }
    first_page_ops.push(Op::EndTextSection);
    first_page_ops.push(Op::RestoreGraphicsState);
    pages.push(PdfPage::new(
        Mm(PAGE_WIDTH_MM),
        Mm(PAGE_HEIGHT_MM),
        first_page_ops,
    ));

    // Every later page starts the table right below the top margin --
    // no title block to make room for.
    for chunk in row_pages {
        let mut ops = vec![Op::SaveGraphicsState, Op::StartTextSection];
        ops.extend(header_row_ops(TOP_START_MM));
        ops.extend(set_font(BuiltinFont::Helvetica, BODY_FONT_SIZE, black()));
        let mut y = TOP_START_MM - ROW_HEIGHT_MM;
        for row in chunk {
            ops.extend(data_row_ops(row, y));
            y -= row_height_mm(row);
        }
        ops.push(Op::EndTextSection);
        ops.push(Op::RestoreGraphicsState);
        pages.push(PdfPage::new(Mm(PAGE_WIDTH_MM), Mm(PAGE_HEIGHT_MM), ops));
    }

    if let Some(shown) = report.truncated_at {
        let mut ops = vec![Op::SaveGraphicsState, Op::StartTextSection];
        ops.extend(set_font(BuiltinFont::HelveticaBold, BODY_FONT_SIZE, gray()));
        ops.extend(show_text_at(
            LEFT_MARGIN_MM,
            TOP_START_MM,
            format!(
                "Results truncated: showing the first {shown} matching events. \
                 Narrow your filters to see the rest."
            ),
        ));
        ops.push(Op::EndTextSection);
        ops.push(Op::RestoreGraphicsState);
        pages.push(PdfPage::new(Mm(PAGE_WIDTH_MM), Mm(PAGE_HEIGHT_MM), ops));
    }

    doc.with_pages(pages)
        .save(&PdfSaveOptions::default(), &mut Vec::new())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::infrastructure::audit_log_pdf::layout::mm_to_pt;

    /// Regression guard for the exact bug that shipped once: `Op::SetTextCursor`
    /// compiles to PDF's relative `Td` operator (see `show_text_at`'s own doc
    /// comment), so calling it repeatedly within one text section made every
    /// cell after the first drift further off-page instead of landing at the
    /// position each call actually asked for -- the PDF rendered as a title
    /// and one lone header cell, nothing else. Asserts the fix directly: each
    /// call produces its own absolute `SetTextMatrix`, unaffected by any call
    /// before it.
    #[test]
    fn show_text_at_produces_independent_absolute_positions() {
        let first = show_text_at(15.0, 232.0, "Time".to_string());
        let second = show_text_at(60.0, 232.0, "Actor".to_string());

        let Op::SetTextMatrix {
            matrix: TextMatrix::Translate(x, y),
        } = &first[0]
        else {
            panic!("expected an absolute SetTextMatrix for the first call");
        };
        assert!((x.0 - mm_to_pt(15.0)).abs() < 0.01);
        assert!((y.0 - mm_to_pt(232.0)).abs() < 0.01);

        let Op::SetTextMatrix {
            matrix: TextMatrix::Translate(x, y),
        } = &second[0]
        else {
            panic!("expected an absolute SetTextMatrix for the second call");
        };
        // The regression: under the old SetTextCursor/Td behaviour this
        // would read 15.0 + 60.0 = 75.0mm worth of pt, not a clean 60.0mm --
        // the second call's position would carry the first call's position
        // baked into it.
        assert!((x.0 - mm_to_pt(60.0)).abs() < 0.01);
        assert!((y.0 - mm_to_pt(232.0)).abs() < 0.01);
    }

    fn sample_row(n: usize) -> AuditLogPdfRow {
        // Same "%Y-%m-%d %H:%M" format the real caller
        // (api::auth_audit_logs::export_audit_logs) produces -- computed
        // via real date rollover (chrono::Duration) rather than a hand-
        // written string, so this fixture can't drift into a plausible-
        // looking but invalid date ("2026-08-010") the way a naive
        // format!("...-0{n}...") would past single digits.
        let created_at = chrono::DateTime::parse_from_rfc3339("2026-08-01T12:00:00Z")
            .unwrap()
            .with_timezone(&chrono::Utc)
            + chrono::Duration::hours(n as i64);

        // Alternates between a bare occurrence and a change-type event so
        // a real render exercises both the empty-Details case and a
        // realistic before/after diff summary in the same sample.
        let (event_type, details) = if n.is_multiple_of(2) {
            (
                "user_deactivated".to_string(),
                "status: active -> deactivated".to_string(),
            )
        } else {
            ("login_succeeded".to_string(), String::new())
        };

        AuditLogPdfRow {
            created_at: created_at.format("%Y-%m-%d %H:%M").to_string(),
            event_type,
            actor_label: "Ada Lovelace (ada@example.com)".to_string(),
            target_label: "—".to_string(),
            ip_address: "203.0.113.1".to_string(),
            details,
        }
    }

    #[test]
    fn renders_a_small_report_to_nonempty_pdf_bytes() {
        let report = AuditLogPdfReport {
            report_title: "UnitPrep Security Log Report".to_string(),
            generated_by: "Admin Admin (admin@example.com)".to_string(),
            generated_at: "2026-08-05T21:00:00Z".to_string(),
            filter_lines: vec![
                "Date range: 2026-08-01 to 2026-08-05".to_string(),
                "Events: All events".to_string(),
                "User: All users".to_string(),
            ],
            rows: (1..=3).map(sample_row).collect(),
            truncated_at: None,
        };

        let bytes = render_audit_log_pdf(&report);

        assert!(!bytes.is_empty());
        assert_eq!(&bytes[0..4], b"%PDF");
    }

    #[test]
    fn renders_a_truncation_note_when_capped() {
        let report = AuditLogPdfReport {
            report_title: "UnitPrep Security Log Report".to_string(),
            generated_by: "Admin Admin (admin@example.com)".to_string(),
            generated_at: "2026-08-05T21:00:00Z".to_string(),
            filter_lines: vec![],
            rows: (1..=3).map(sample_row).collect(),
            truncated_at: Some(3),
        };

        let bytes = render_audit_log_pdf(&report);

        assert!(!bytes.is_empty());
        assert_eq!(&bytes[0..4], b"%PDF");
    }

    #[test]
    fn paginates_across_multiple_pages_for_a_large_row_count() {
        // Comfortably more rows than fit on one page at ROW_HEIGHT_MM
        // spacing -- forces the multi-page path to actually run.
        let report = AuditLogPdfReport {
            report_title: "UnitPrep Security Log Report".to_string(),
            generated_by: "Admin Admin (admin@example.com)".to_string(),
            generated_at: "2026-08-05T21:00:00Z".to_string(),
            filter_lines: vec![],
            rows: (1..=200).map(sample_row).collect(),
            truncated_at: None,
        };

        let bytes = render_audit_log_pdf(&report);

        assert!(!bytes.is_empty());
        assert_eq!(&bytes[0..4], b"%PDF");
    }

    #[test]
    #[ignore = "manual visual inspection only -- writes to /tmp"]
    fn write_sample_pdf_to_disk_for_manual_inspection() {
        let report = AuditLogPdfReport {
            report_title: "UnitPrep Security Log Report".to_string(),
            generated_by: "Boris Maksimov (bmaksimov@quikstor.com)".to_string(),
            generated_at: "2026-08-05T22:00:00Z".to_string(),
            filter_lines: vec![
                "Date range: 2026-08-01 to 2026-08-05".to_string(),
                "Events: All events".to_string(),
                "Users: All users".to_string(),
                "IP address: Any".to_string(),
            ],
            rows: (1..=60)
                .map(sample_row)
                .enumerate()
                .map(|(index, mut row)| {
                    // Row 4 (n=5, an otherwise-empty-Details login event)
                    // gets an artificially long Details value so this
                    // manual-inspection render actually exercises wrapping
                    // instead of only ever showing the short, single-line
                    // "status: active -> deactivated" the fixture
                    // otherwise alternates in.
                    if index == 4 {
                        row.details = "Session token rotated after step-up re-authentication; \
                             previous session revoked from IP 203.0.113.1 due to a role change \
                             from OnboardingManager to Admin"
                            .to_string();
                    }
                    row
                })
                .collect(),
            truncated_at: None,
        };

        let bytes = render_audit_log_pdf(&report);
        std::fs::write("/tmp/sample_audit_log.pdf", bytes).unwrap();
    }

    #[test]
    fn renders_with_zero_rows() {
        let report = AuditLogPdfReport {
            report_title: "UnitPrep Security Log Report".to_string(),
            generated_by: "Admin Admin (admin@example.com)".to_string(),
            generated_at: "2026-08-05T21:00:00Z".to_string(),
            filter_lines: vec!["No matching events.".to_string()],
            rows: vec![],
            truncated_at: None,
        };

        let bytes = render_audit_log_pdf(&report);

        assert!(!bytes.is_empty());
        assert_eq!(&bytes[0..4], b"%PDF");
    }
}
