#!/usr/bin/env bash
# Regenerates SCHEMA.sql -- the read-only "current cumulative schema" reference
# -- from a database built by applying every migration in migrations/ to the
# local ephemeral test-db (docker-compose.yml's `test-db` service).
#
# Why the test-db and not the Neon dev database: it is built purely from the
# migrations, so the file always reflects exactly what the migrations produce
# (a long-lived dev database can carry hand-applied drift), it needs no
# credentials, and it never touches a shared database.
#
# Usage (from anywhere; needs docker and a running test-db):
#   docker compose --profile test up -d test-db     # if it is not running
#   ./scripts/bootstrap_test_db.sh                  # applies every migration
#   ./scripts/regenerate_schema_sql.sh
#
# Run it after any chunk that adds a migration, then commit SCHEMA.sql.
set -euo pipefail

cd "$(dirname "$0")/.."

container="${TEST_DB_CONTAINER:-unitprep-api-test-db-1}"
db="${TEST_DB_NAME:-unitprep_test}"
migrations="$(ls migrations/*.up.sql | wc -l | tr -d ' ')"
generated="$(date -u +%Y-%m-%d)"

if ! docker ps --format '{{.Names}}' | grep -qx "$container"; then
    echo "test-db container '$container' is not running." >&2
    echo "Start it with: docker compose --profile test up -d test-db && ./scripts/bootstrap_test_db.sh" >&2
    exit 1
fi

{
    cat <<EOF
-- Current cumulative schema, generated by scripts/regenerate_schema_sql.sh
-- from a database built by applying every migration in migrations/ to the
-- local test-db, via
--   pg_dump --schema-only --no-owner --no-privileges
-- Read-only reference, not applied by sqlx and not part of the migrations/
-- directory -- the ${migrations} incremental migrations under migrations/
-- remain the actual source of truth and the real "how did we get here"
-- history. This file exists so a newcomer (human or AI) can see current
-- table/column/RLS/index shape in one place without reading them all in
-- order.
--
-- A point-in-time snapshot, not live-synced: regenerate after any
-- schema-changing migration lands (./scripts/regenerate_schema_sql.sh).
-- psql's per-dump \\restrict/\\unrestrict guard lines (a random token that
-- changes on every dump) are stripped so a regeneration only shows real
-- schema changes in the diff.
-- Generated ${generated}.

EOF
    docker exec "$container" pg_dump -U postgres -d "$db" \
        --schema-only --no-owner --no-privileges \
        | grep -vE '^\\(un)?restrict '
} > SCHEMA.sql

echo "SCHEMA.sql regenerated from ${migrations} migrations ($(wc -l < SCHEMA.sql) lines)."
